# Project: 13.1.1格式化输入输出
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 13.1.1.main.o
LINKOBJ  = 13.1.1.main.o
LIBS     = -L"E:/biancheng/Dev-Cpp/MinGW64/lib" -L"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/biancheng/Dev-Cpp/MinGW64/include" -I"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/biancheng/Dev-Cpp/MinGW64/include" -I"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 13.1.1格式化输入输出.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

13.1.1.main.o: 13.1.1.main.c
	$(CC) -c 13.1.1.main.c -o 13.1.1.main.o $(CFLAGS)
