# Project: test
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o acllib.o
LINKOBJ  = main.o acllib.o
LIBS     = -L"E:/biancheng/Dev-Cpp/MinGW64/lib" -L"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libwinmm.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmingw32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libgdi32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libkernel32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libole32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/liboleaut32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuser32.a ../../../../biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuuid.a -g3
INCS     = -I"E:/biancheng/Dev-Cpp/MinGW64/include" -I"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/biancheng/Dev-Cpp/MinGW64/include" -I"E:/biancheng/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/biancheng/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = test.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
